services:

  gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: gateway/Gateway/Gateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Key=${JWT_KEY}
      - Jwt__AccessTokenExpirationMinutes=${ACCESS_TOKEN_LIFETIME}
      - Jwt__RefreshTokenExpirationDays=${REFRESH_TOKEN_LIFETIME}
      - Kestrel__Endpoints__Https__Certificate__Path=${CERTS_PATH}
      - Kestrel__Endpoints__Https__Certificate__Password=${CERTS_PASSWORD}
      - Kestrel__Endpoints__Https__Url=https://+:5001
      - DOTNET_RUNNING_IN_CONTAINER=true;
    networks:
      - public
      - internal
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./certs:/app/certs:ro

  authentication-service:
    image: authentication-service:latest
    build:
     context: .
     dockerfile: services/AuthenticationService/Api/Dockerfile
    environment:
      - HmacSecret=${HMAC_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Key=${JWT_KEY}
      - Jwt__AccessTokenExpirationMinutes=${ACCESS_TOKEN_LIFETIME}
      - Jwt__RefreshTokenExpirationDays=${REFRESH_TOKEN_LIFETIME}
      - ConnectionStrings__AuthDbConnection=Host=authentication-service-database;Port=5432;Database=auth_db;Username=developer;Password=${AUTH_DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://authentication-service:8080
    networks:
      - public
      - internal
      - authentication-internal
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      authentication-service-database:
        condition: service_healthy

  equipment-service:
    image: equipment-service:latest
    build:
      context: .
      dockerfile: services/EquipmentService/EquipmentService.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:7070
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=equipment-service-database;Port=5432;Database=equipment;Username=developer;Password=${EQUIPMENT_DB_PASSWORD}
    networks:
      - public
      - internal
      - equipment-internal
    ports:
      - "8081:7070"
    depends_on:
      equipment-service-database:
        condition: service_healthy
  
  authentication-service-database:
    image: postgres:latest
    container_name: authentication-database
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    networks:
      - public
      - authentication-internal
    volumes:
      - auth-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  equipment-service-database:
    image: postgres:latest
    container_name: equipment-database
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: equipment
      POSTGRES_PASSWORD: ${EQUIPMENT_DB_PASSWORD}
    networks:
      - public
      - equipment-internal
    volumes:
      - equipment-db-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  public:
    internal: false

  internal:
    internal: true

  authentication-internal:
    internal: true

  equipment-internal:
    internal: true

volumes:
  auth-db-volume:
  technical-reports-volume:
  equipment-db-volume: