// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SparePartsWarehouse.Infrastructure;

#nullable disable

namespace SparePartsWarehouse.Infrastructure.Migrations
{
    [DbContext(typeof(SparePartsWarehouseContext))]
    [Migration("20251024080056_SupplyConstructorFix")]
    partial class SupplyConstructorFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SparePartsWarehouse.Domain.Entities.SparePart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("CompatibleEquipmentModels")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("compatible_equipment_models");

                    b.Property<DateTime>("FirstTimeDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_time_delivered_at");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.HasKey("Id");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.HasIndex("LastUpdatedAt", "Id")
                        .IsDescending();

                    b.ToTable("spare_parts", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.Domain.Entities.Supply", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ArrivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.ToTable("supply", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.Domain.Entities.Supply", b =>
                {
                    b.OwnsMany("SparePartsWarehouse.Domain.Entities.SupplyItem", "SupplyItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("amount");

                            b1.Property<string>("CompatibleEquipmentModels")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("compatible_equipment_models");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("model");

                            b1.Property<Guid>("supply_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("supply_id");

                            b1.ToTable("supply_item", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("supply_id");
                        });

                    b.Navigation("SupplyItems");
                });
#pragma warning restore 612, 618
        }
    }
}
