// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SparePartsWarehouse.Infrastructure;

#nullable disable

namespace SparePartsWarehouse.Infrastructure.Migrations
{
    [DbContext(typeof(SparePartsWarehouseContext))]
    partial class SparePartsWarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SparePartsWarehouse.Domain.Entities.SparePart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("CompatibleEquipmentModels")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("compatible_equipment_models");

                    b.Property<DateTime>("FirstTimeDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_time_delivered_at");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("LastUpdatedAt", "Id")
                        .IsDescending();

                    b.ToTable("spare_parts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
